vich_uploader:
    db_driver: orm

    mappings:
        brand_logo:
            uri_prefix: /images/brands
            upload_destination: '%kernel.project_dir%/public/images/brands'
        category_image:
            uri_prefix: /images/categories
            upload_destination: '%kernel.project_dir%/public/images/categories'
        equipment_image:
            uri_prefix: /images/equipments
            upload_destination: '%kernel.project_dir%/public/images/equipments'
