#!/bin/sh
rsync -av ./ c167_multimedia@lapin.web.wellhosted.ch:/web --include=public/build --include=vendor --exclude-from=.gitignore --exclude=".*" --exclude=deploy --exclude=assets --exclude=migrations
ssh c167_multimedia@lapin.web.wellhosted.ch 'cd /web && php8.1 bin/console cache:clear'