#!/bin/sh
npm run build
#ssh c167_multimedia@lapin.web.wellhosted.ch 'cd ~/sites/beta.espace-multimedia.drutz.ch/public && rm -rf build'
rsync -av ./ c167_multimedia@lapin.web.wellhosted.ch:~/web --include=public/build --include=vendor --exclude-from=.gitignore --exclude=".*" --exclude=deploy --exclude=assets
ssh c167_multimedia@lapin.web.wellhosted.ch 'cd ~/web/beta.espace-multimedia.drutz.ch && php bin/console cache:clear'